{% set name = "ginsim-python" %}
{% set version = "9999" %}
package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  path: ../

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  noarch: python

requirements:
  build:
    - python
    - pip
    - ginsim

  run:
    - python
    - ginsim
    - py4j
    - colomoto_jupyter >=0.6.3

about:
  home:  http://ginsim.org/
  summary: 'GINsim and bioLQM python interface'
  license_family: LGPL
  license: LGPL v3+/CeCILL-C


