{% set name = "ginsim-python" %}
{% set version = "0.3.5" %}
package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  git_rev: v{{ version }}
  git_url: https://github.com/GINsim/GINsim-python.git

channels:
  - colomoto
  - potassco

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  noarch: python

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - ginsim
    - py4j
    - colomoto_jupyter

about:
  home:  http://ginsim.org/
  summary: 'GINsim and bioLQM python interface'
  license_family: LGPL
  license: LGPL v3+/CeCILL-C


