name: Publish conda package

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Conda publish
      uses: docker://colomoto/conda-builder:latest
      with:
        subdir: conda
        anaconda_user: colomoto
        anaconda_token: ${{ secrets.ANACONDA_TOKEN }}
